### ISSUE TITLE
msfp_sequence

### ISSUE THREAD

**Issue by elementalfire23** [MicrosoftDocs/customer-voice#16]
msfp_sequence in the backend is actually msfp_order

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8965fd6-1dab-fbb8-50bd-93c7b9f5a821
* Version Independent ID: bc4c9fe8-b5b8-7e02-7734-20fc583fe98c
* Content: [msfp_question Entity Reference - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/developer/reference/entities/msfp_question#feedback)
* Content Source: [fp-docs/developer/reference/entities/msfp_question.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/developer/reference/entities/msfp_question.md)
* Service: **forms-pro**
* GitHub Login: @susikka
* Microsoft Alias: **susikka**

**Comment by susikka** [comment]
@elementalfire23 Thanks for creating this issue. Will investigate this and get back.

**Comment by sbmjais** [comment]
This issue was in Forms Pro. The entities are updated in Customer Voice. [https://docs.microsoft.com/en-us/dynamics365/customer-voice/developer/entity-reference](https://docs.microsoft.com/en-us/dynamics365/customer-voice/developer/entity-reference)
Closing this task.
