### ISSUE TITLE
Is this within Graph API

### ISSUE THREAD

**Issue by cconrado** [MicrosoftDocs/customer-voice#22]
I don't understand the context of this. What is it referencing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5a58bc0-4f2d-cf0c-5858-20ec9f3bcc6e
* Version Independent ID: 30d1a685-0b34-b946-1a6a-d2f7adc712df
* Content: [Developer guide for Microsoft Forms Pro - Microsoft Forms Pro](https://docs.microsoft.com/en-us/forms-pro/developer/developer-guide)
* Content Source: [fp-docs/developer/developer-guide.md](https://github.com/MicrosoftDocs/forms-pro/blob/master/fp-docs/developer/developer-guide.md)
* Service: **forms-pro**
* GitHub Login: @susikka
* Microsoft Alias: **susikka**

**Comment by colinbrislawn** [comment]
These appears to be [entities](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/entity-overview), which I guess are part part of the [Common Data Service](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-intro). 🤷  
So... is Forms Pro essentially a [Microsoft Power App](https://docs.microsoft.com/en-us/power-platform/) built and sold by Microsoft?

**Comment by sbmjais** [comment]
This is regarding to Forms Pro which is now Customer Voice. A new entity reference guide is available: https://docs.microsoft.com/en-us/dynamics365/customer-voice/developer/entity-reference
Closing this task.
