### ISSUE TITLE
Add a response to survey via rest api

### ISSUE THREAD

**Issue by jst84** [MicrosoftDocs/customer-voice#32]
Hi! I'm trying to add a response to an existing survey, but something goes wrong.
The flow is the following:

POST https://[tenant].crm3.dynamics.com/api/data/v9.0/msfp_surveyresponses
-- take the activityId
POST https://[tenant].crm3.dynamics.com/api/data/v9.0/msfp_questionresponses

both operations get the status code 204.

But, if I go to the portal I cannot see the answer (I see the answer only in the detailed view).

Does anyone know the right way to do this operation?
![forms](https://user-images.githubusercontent.com/25516048/82895372-6a6fc300-9f54-11ea-8ba1-e9ff47df03d9.png)

Thanks,
Stefano.

**Comment by jst84** [comment]
Is there anyone who can help me? Thanks a lot!

**Comment by sbmjais** [comment]
Thanks for contacting us. The UI attached in the issue of Microsoft Forms. You can contact Microsoft Forms support by using the Contact us link on [this page](https://support.microsoft.com/en-in/forms).
Closing this issue.
