### ISSUE TITLE
Is the "Dynamics 365 Operations" license same as "Dynamics 365 Project Operations"?

### ISSUE THREAD

**Issue by zdehav** [MicrosoftDocs/customer-voice#40]
Hello,

In chapter "Enable Dynamics 365 Customer Voice for user with Dynamics 365 enterprise licenses" is listed "Dynamics 365 Operations". But on [Dynamics 365 pricing page](https://dynamics.microsoft.com/en-us/pricing/) is listed "Dynamics 365 Project Operations". Is this same product?

Thanks for reply
Zdenek Havel

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb076b68-c826-103a-617e-0d3a54295977
* Version Independent ID: 1a0830d6-601a-2e0b-c3f3-886dd4c31c70
* Content: [Purchase Dynamics 365 Customer Voice and additional license](https://docs.microsoft.com/en-us/dynamics365/customer-voice/purchase#feedback)
* Content Source: [cv-docs/purchase.md](https://github.com/MicrosoftDocs/customer-voice/blob/master/cv-docs/purchase.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Hi @zdehav - Thanks for the feedback. We have updated the document with the correct product name.

Closing this issue.
