### ISSUE TITLE
How to use a variable instead of the fixed strings in embed code

### ISSUE THREAD

**Issue by malkhawaja** [MicrosoftDocs/customer-voice#41]
Hi,
I am embedding the survey inside a Model-Driven Power App using an html webresource, and I want to pass variables in this code line instead of the static strings... so instead of this:
`<script>
	 window.addEventListener('load', function () {
            renderSurvey("surveyDiv", "Bert", "Hair", "bert.hair@contoso.com", "Product Overview");
        }, false);
</script>
`
I want this:
`<script>
          var FirstName = "John";
	 window.addEventListener('load', function () {
            renderSurvey("surveyDiv", FirstName, "Hair", "bert.hair@contoso.com", "Product Overview");
        }, false);
</script>`
but this way the addEventListener cannot see the variable, so how can I achieve this? noting that I am not a pro developer

**Comment by sbmjais** [comment]
Thanks for contacting us. The survey's embed code generated from Customer Voice will contain variables. The div container and a method to call the renderSurvey function must be defined manually. This sample code in the document uses static user details for demonstration purposes, but you can provide a function that retrieves the logged-in user details.

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
