### ISSUE TITLE
Licensing description does not match Licensing guide document

### ISSUE THREAD

**Issue by tdagys** [MicrosoftDocs/customer-voice#42]
Hi,

It it seems Customer Voice licensing and pricing changed from Feb 2021. And this description does not match Dynamics 365 Licensing Guide Feb 2021.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb076b68-c826-103a-617e-0d3a54295977
* Version Independent ID: 1a0830d6-601a-2e0b-c3f3-886dd4c31c70
* Content: [Purchase Dynamics 365 Customer Voice and additional license](https://docs.microsoft.com/en-us/dynamics365/customer-voice/purchase)
* Content Source: [cv-docs/purchase.md](https://github.com/MicrosoftDocs/customer-voice/blob/master/cv-docs/purchase.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Hi @tdagys - Thanks for the feedback. We are working on updating the document as per license update.

**Comment by sbmjais** [comment]
Hi @tdagys - We have updated the document as per the latest update.

Closing this issue.
