### ISSUE TITLE
Design Tab?  Format bar?  Not appearing.

### ISSUE THREAD

**Issue by blogmom** [MicrosoftDocs/customer-voice#43]
There is no Design Tab, and no Format Bar as shown in the screenshot.  Using Edge 88.0.705.68 (Official build) (64-bit) to create and edit the form.  Also tried creating and editing a Form/Survey in Teams, not there either.  Please either edit the Page or advise customers how to access the mysterious Design Tab.  Thank you.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8c7aebe-9e70-34ef-4373-0a185b1b2a5e
* Version Independent ID: 27e8510b-c313-f7f1-388a-620d3dffb258
* Content: [Format text in a survey](https://docs.microsoft.com/en-us/dynamics365/customer-voice/survey-text-format)
* Content Source: [cv-docs/survey-text-format.md](https://github.com/MicrosoftDocs/customer-voice/blob/master/cv-docs/survey-text-format.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
@blogmom - Thanks for contacting us. The Design tab and the formatting bar are visible in the surveys created in Dynamics 365 Customer Voice. Please confirm if you are using Dynamics 365 Customer Voice or Microsoft Forms.

**Comment by blogmom** [comment]
Thank you for replying.  I did not notice this page was under Dynamics.  I am using Microsoft Forms.  It sure would be nice if formatting like this was possible in Microsoft Forms too.  Please go ahead and close this issue as resolved with my apologies.

**Comment by sbmjais** [comment]
Thanks @blogmom. You can contact Microsoft Forms support by using the **Contact us** link on [this page](https://support.microsoft.com/en-in/forms).
