### ISSUE TITLE
Instructions No Longer Valid - Edit in Advanced Mode

### ISSUE THREAD

**Issue by Komikal** [MicrosoftDocs/customer-voice#44]
Details under section **Specify value in a flow** utilize the **Edit in Advanced Mode** which is no longer available.  The instructions need to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7db8ceb-5afc-512e-fb5b-b6554730aa5e
* Version Independent ID: 7a64a2a5-30a1-b997-468d-d2c15a0314c0
* Content: [Personalize a survey](https://docs.microsoft.com/en-us/dynamics365/customer-voice/personalize-survey)
* Content Source: [cv-docs/personalize-survey.md](https://github.com/MicrosoftDocs/customer-voice/blob/master/cv-docs/personalize-survey.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for the feedback. We are able to follow the steps mentioned in the document. Please share the steps that you are seeing.

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
