### ISSUE TITLE
Edit/Delete custom email addresses

### ISSUE THREAD

**Issue by chill8675309** [MicrosoftDocs/customer-voice#45]
The steps to edit or delete a custom email address does not reflect the actual behaviour. The ellipsis is for editing the domain, not the individual email addresses. I've attempted to edit and delete addresses from within this screen however the changes are not retained after closing the confirmation screen. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de7f630e-4f17-e26e-9301-104da653b3b6
* Version Independent ID: c6030265-1d20-3981-5540-3fc387df4176
* Content: [Customize the From address of the email](https://docs.microsoft.com/en-us/dynamics365/customer-voice/customize-sender-email)
* Content Source: [cv-docs/customize-sender-email.md](https://github.com/MicrosoftDocs/customer-voice/blob/master/cv-docs/customize-sender-email.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for the feedback. We have updated the documentation: [https://docs.microsoft.com/en-us/dynamics365/customer-voice/customize-sender-email](https://docs.microsoft.com/en-us/dynamics365/customer-voice/customize-sender-email). Closing this issue.
