### ISSUE TITLE
Re: Weight

### ISSUE THREAD

**Issue by dsghi** [MicrosoftDocs/customer-voice#47]
Weight is mentioned, but it's not clear if a lower number is better. The default is identified. In the document text below an example is used regarding food packaging, however, it's not clear _how_ the weight is changed to achieve the desired result:

"Weight: Weight allows you to measure the importance of a particular question higher or lower than other questions. For example, let's say you have a survey asking for customer feedback regarding the food delivery service. There are three questions that ask about the timeliness of the service, packaging of the food, and quality of the food. In this example, the quality of food is more important than the packaging of food. Therefore, a higher weight will be assigned to the question about quality, giving a more accurate and relevant result.

By default, the value of weight for all questions is 1."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31387b2c-e7d9-5399-4c7d-4cefaefc6691
* Version Independent ID: 8abe21df-e444-8b09-8cd6-d4794585b43c
* Content: [Add scoring to a survey](https://docs.microsoft.com/en-us/dynamics365/customer-voice/survey-scoring)
* Content Source: [cv-docs/survey-scoring.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/survey-scoring.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for the feedback. We have updated the documented: [https://docs.microsoft.com/en-us/dynamics365/customer-voice/survey-scoring](https://docs.microsoft.com/en-us/dynamics365/customer-voice/survey-scoring)
Closing this issue.
