### ISSUE TITLE
Can you customize the sender (from) name? 

### ISSUE THREAD

**Issue by woodyarray** [MicrosoftDocs/customer-voice#48]
We don't want the actual sender's name appear in the FROM when a user receives an invitation to a survey.

Is there anyway to change that?

Does the API call to formsPro have a "from" field that we can modify in LogicApps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de7f630e-4f17-e26e-9301-104da653b3b6
* Version Independent ID: c6030265-1d20-3981-5540-3fc387df4176
* Content: [Customize the sender's email address to send survey invitations](https://docs.microsoft.com/en-us/dynamics365/customer-voice/customize-sender-email)
* Content Source: [cv-docs/customize-sender-email.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/customize-sender-email.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
@woodyarray - Thanks for contacting us. The default email cannot be modified. However, you can create a custom email. The steps are documented at: [https://docs.microsoft.com/en-us/dynamics365/customer-voice/customize-sender-email](https://docs.microsoft.com/en-us/dynamics365/customer-voice/customize-sender-email)
Closing this issue.
