### ISSUE TITLE
Create Invite link using Service Account or using Server-Server API

### ISSUE THREAD

**Issue by nagaretn** [MicrosoftDocs/customer-voice#49]
Hi,
In the context of creating Survey invitation link through Power Apps or via Logic App, the connector is using a Users Account. However if the Survey is to be sent for an Enterprise App like CRM or ERP based on some trigger, we would require the survey link to be created using Service Account or using an registered App. This will avoid survey to be dependent on a particular admin user account.
Any thoughts on how this could be done !

Regards,
Ganesh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55424c6-2155-d07c-af91-a0d1d07b479f
* Version Independent ID: dc01a248-e598-044c-6b10-bc321dfd1e9e
* Content: [Connect Dynamics 365 Customer Voice with your environment](https://docs.microsoft.com/en-us/dynamics365/customer-voice/connect-environment)
* Content Source: [cv-docs/connect-environment.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/connect-environment.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: https://docs.microsoft.com/dynamics365/get-started/support/
Closing this issue.
