### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/customer-voice#52]
Hi guys, a very minor typo in this sentance you may want to correct: "You can use then use this custom email address to send survey invitations to your customers" (delete first "use")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de7f630e-4f17-e26e-9301-104da653b3b6
* Version Independent ID: c6030265-1d20-3981-5540-3fc387df4176
* Content: [Customize the sender's email address to send survey invitations](https://docs.microsoft.com/en-us/dynamics365/customer-voice/customize-sender-email)
* Content Source: [cv-docs/customize-sender-email.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/customize-sender-email.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for the feedback @HandyAndyOnGitHub. We've updated the document.
Closing this task.
