### ISSUE TITLE
In survey form, each section start with question number 1

### ISSUE THREAD

**Issue by mrmichaellei** [MicrosoftDocs/customer-voice#53]
I created a survey form and divided into 3 sections. I wanted to start each section with question number 1. 
How to do it ?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96fdc2cf-c0bb-35b8-1fa5-1ecf52d386c7
* Version Independent ID: 19c5fd78-d488-6771-3bc4-81b04af2e5d6
* Content: [Create a multiple-page survey](https://docs.microsoft.com/en-us/dynamics365/customer-voice/create-multipage-survey)
* Content Source: [cv-docs/create-multipage-survey.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/create-multipage-survey.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks @mrmichaellei for contacting us. Currently, you can either hide the question numbers or have the numbers continued across sections. Please submit the idea for restarting question number in each section at [aka.ms/customervoiceideas](aka.ms/customervoiceideas).

Closing this issue.
