### ISSUE TITLE
German Translation is misleading

### ISSUE THREAD

**Issue by Tiglat1** [MicrosoftDocs/customer-voice#54]
The German version states that a tenant with Dynamics 365 enterprise products has  2,000 Customer Voice responses per month included. This is not correct: As the English version of the article states correctly, a tenant with **select** Dynamics 365 enterprise products has 2,000 responses per month included.

Based on the German version of the article customers assume that any Dynamics 365 enterprise product includes the 2,000 responses per month.

Aktivieren Sie Dynamics 365 Customer Voice für Benutzer ohne Unternehmenslizenz von Dynamics 365

Ein Mandant, der Dynamics 365 Unternehmensprodukte wählt, hat 2000 Antworten pro Monat, die auf Mandantenebene enthalten sind (unabhängig davon, wie viele Plätze der Mandant hat). Wenn die kostenlosen Antworten aufgebraucht sind, können Sie zusätzliche Antworten erwerben, wie im Abschnitt Kaufen Sie zusätzliche Antworten erwähnt.

,Purchase Dynamics 365 Customer Voice: 
Enable Dynamics 365 Customer Voice for users with Dynamics 365 enterprise licenses
A tenant with select Dynamics 365 enterprise products has 2,000 responses per month included at the tenant level (irrespective of how many seats the tenant has). If the free responses are exhausted, you can purchase additional responses as mentioned in the Purchase additional responses section.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fb076b68-c826-103a-617e-0d3a54295977
* Version Independent ID: 1a0830d6-601a-2e0b-c3f3-886dd4c31c70
* Content: [Kaufen von Dynamics 365 Customer Voice und zusätzlicher Lizenz](https://docs.microsoft.com/de-de/dynamics365/customer-voice/purchase)
* Content Source: [cv-docs/purchase.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/purchase.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for your feedback. We have informed the Localization team about this issue in our localized content. Closing the issue.
