### ISSUE TITLE
How to access the branching rules? 

### ISSUE THREAD

**Issue by tokiosam** [MicrosoftDocs/customer-voice#55]
Thanks for sharing.

Is the pro version (MS Dynamics license) needed to do this? 

Thanks.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dff4c66-23f7-d3d1-f60c-db15608b9f3b
* Version Independent ID: cbde5db2-7471-723b-9b6b-9d055941ff36
* Content: [Create a branching rule for a survey](https://docs.microsoft.com/en-us/dynamics365/customer-voice/create-branching-rule)
* Content Source: [cv-docs/create-branching-rule.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/create-branching-rule.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
@tokiosam - Thanks for contacting us. Dynamics 365 Customer Voice is included with select Dynamics 365 enterprise products such as Dynamics 365 Sales Enterprise and Dynamics 365 Customer Service Enterprise. If you have other Dynamics 365 products or don't have a Dynamics 365 subscription, you may purchase Dynamics 365 Customer Voice separately. For a complete list of select Dynamics 365 enterprise products, see [Dynamics 365 Customer Voice pricing](https://dynamics.microsoft.com/customer-voice/pricing/). More information is at: [Purchase Dynamics 365 Customer Voice](https://docs.microsoft.com/en-us/dynamics365/customer-voice/purchase)

No additional license is required for the branching rules feature.

Please let us know if this resolves your issue.

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
