### ISSUE TITLE
Many Thanks 

### ISSUE THREAD

**Issue by Elrasheid2** [MicrosoftDocs/customer-voice#56]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b57afd33-2977-a71d-a206-2a4eba82b706
* Version Independent ID: e3fdd5da-ba7f-875f-ee95-7b9283bdd205
* Content: [Embed a survey in a webpage](https://docs.microsoft.com/en-us/dynamics365/customer-voice/embed-web-page)
* Content Source: [cv-docs/embed-web-page.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/embed-web-page.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for your feedback. We’re glad our content helped you. Closing the issue.
