### ISSUE TITLE
Please explain about recurring surveys

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/customer-voice#57]
Hello,
Please check with the product group and update this documentation page with features or suggested ways to work with recurring surveys.

For example, sending monthly surveys to the same customer. So, we can track user experience for each month.
Should we create a new survey for each month? or should we re-use existing survey to send to (same) customers, each month? how will this reflect to reports then?

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e270f9b-420e-4638-2f97-2d89d119d3fa
* Version Independent ID: 57f68427-8967-1489-543a-fd39e77018ca
* Content: [Plan a survey](https://docs.microsoft.com/en-us/dynamics365/customer-voice/plan-survey)
* Content Source: [cv-docs/plan-survey.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/plan-survey.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
Thanks for your feedback. The trend analysis on reports is currently not available. You can use either of the options you mentioned. The responses will be treated as independent.

For product-related feedback, visit the [Customer Voice Ideas](https://aka.ms/customervoiceideas) page, and share your new feature requirements or ideas.
Closing this issue.
