### ISSUE TITLE
More datails on data flow?

### ISSUE THREAD

**Issue by robin0821** [MicrosoftDocs/customer-voice#59]
Hi sbmjais,

Thank you for your fabulous explaination on the data flow. 

We are a health provider in Australia. We'd very much likely to use the Customer Voice product. However, by legal restriction / regulations, all client identifiable data cannot be flow outside of Australia. Is there anyway that we can overcome this e.g., skip the Customer Voices Service step and store the data directly into Dataverse?

Do you happen to know any organisations from healthcare sectors who are currently using the MS Customer Voice?

Cheers,
Robin

**Comment by dafi902** [comment]
Close

**Comment by dafi902** [comment]
>

**Comment by sbmjais** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [https://docs.microsoft.com/dynamics365/get-started/support/](https://docs.microsoft.com/dynamics365/get-started/support/)
Closing this issue.
