### ISSUE TITLE
Missing crucial information for integration

### ISSUE THREAD

**Issue by Panoone** [MicrosoftDocs/customer-voice#62]
Nowhere in this article does it mention the need to enable a feature switch for complete integration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55424c6-2155-d07c-af91-a0d1d07b479f
* Version Independent ID: dc01a248-e598-044c-6b10-bc321dfd1e9e
* Content: [Connect Dynamics 365 Customer Voice with your environment](https://docs.microsoft.com/en-us/dynamics365/customer-voice/connect-environment)
* Content Source: [cv-docs/connect-environment.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/connect-environment.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Panoone. This issue has been assigned to the doc author for review.

**Comment by sbmjais** [comment]
Thanks for the feedback. There's no feature switch available for this feature. Please elaborate your query.

**Comment by sbmjais** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
