### ISSUE TITLE
How to send email with survey from account of user who click "Send survey" button?

### ISSUE THREAD

**Issue by 0x29aw** [MicrosoftDocs/customer-voice#65]
By default survey is sent from <surveys@semail...> email address. I want to send an email with survey url from email address of user who click "Send survey" button. It must be dynamically- any user with permissions can click this button. How to do it? It is possible?

**Comment by sbmjais** [comment]
Thanks for the feedback. You can't send an email from the logged-in user's account. However, you can configure custom domain. For more information, see [Customize the sender's email address](https://learn.microsoft.com/en-us/dynamics365/customer-voice/customize-sender-email).

Closing this issue.
