### ISSUE TITLE
RegardingID: ID of the entity needs to be replaced with ID of the record

### ISSUE THREAD

**Issue by DASNavax** [MicrosoftDocs/customer-voice#66]
[Enter feedback here]
"RegardingID: ID of the entity" as requirement is misleading! It's about the ID of the record (GUID) that has to be linked!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28c00c4c-4776-de19-75b1-2198a0c2d5c3
* Version Independent ID: 023b12ff-942a-7830-cad7-c480be10cb61
* Content: [Send a survey by using email](https://docs.microsoft.com/en-us/dynamics365/customer-voice/send-survey-email#feedback)
* Content Source: [cv-docs/send-survey-email.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/send-survey-email.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DASNavax. This issue has been assigned to the doc author for review.

**Comment by sbmjais** [comment]
Thanks for the feedback. We've updated the document to clarify the description.

Closing this issue.
