### ISSUE TITLE
The CNAME records should not contain the domain suffix

### ISSUE THREAD

**Issue by KoenJanssensPD** [MicrosoftDocs/customer-voice#67]
I have lost quite some hours trying to add a custom domain.
It appears (as noted [here](https://d365topicsbydk.com/2021/10/10/add-custom-domain-in-dynamics-365-customer-voice-survey/)) that the domain suffix for the CNAME records should not be included... (I am not using GoDaddy, but another domain provider)

> The name values entered in DNS Records in GoDaddy should not have the domain suffix for names. The value in DNS should be fpeurkey1_domainkey and fpeurkey2_domainkey instead of fpeurkey1_domainkey.devisdemo.com and fpeurkey2_domainkey.devisdemo.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de7f630e-4f17-e26e-9301-104da653b3b6
* Version Independent ID: c6030265-1d20-3981-5540-3fc387df4176
* Content: [Customize the sender's email address to send survey invitations](https://docs.microsoft.com/en-us/dynamics365/customer-voice/customize-sender-email)
* Content Source: [cv-docs/customize-sender-email.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/customize-sender-email.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KoenJanssensPD. This issue has been assigned to the doc author for review.

**Comment by sbmjais** [comment]
Thanks for the feedback. We've already included the information about not to duplicate domain names in a CNAME record at: https://learn.microsoft.com/en-us/dynamics365/customer-voice/customize-sender-email#cname-record

Closing this issue.
