### ISSUE TITLE
File Upload - Where Does It Go?

### ISSUE THREAD

**Issue by gmcmenimen** [MicrosoftDocs/customer-voice#68]
When you add the file upload type question, I can see that if I upload a file, it looks like it goes into my personal OneDrive in the Apps.  How can this be adjusted to go to another folder in Dynamics?  I would assume that would be an option if I want to recover what was uploaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00adc4ef-e054-91d4-b155-ccddc094fdbe
* Version Independent ID: bb34da30-d158-e1a5-c3ce-c9f6906829d8
* Content: [Question types available](https://docs.microsoft.com/en-us/dynamics365/customer-voice/available-question-types)
* Content Source: [cv-docs/available-question-types.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/available-question-types.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gmcmenimen. This issue has been assigned to the doc author for review.

**Comment by sbmjais** [comment]
Thanks for your feedback. We are working towards updating the File upload functionality. The details are published at: https://learn.microsoft.com/en-us/dynamics365-release-plan/2022wave2/customer-voice/dynamics365-customer-voice/allow-file-upload-option-external-survey-responders.

Closing this issue.
