### ISSUE TITLE
Naming and text issues 

### ISSUE THREAD

**Issue by diyd365** [MicrosoftDocs/customer-voice#69]
[Enter feedback here]
Please rename common data service to dataverse in the diagram.
Also, the text in the diagram needs to be in a lighter colour as it’s not visible in dark theme. 
see attachment.
Thanks!
![1025AB4E-E47A-484C-B92C-6B07E3EA3136](https://user-images.githubusercontent.com/54136780/221981971-5701b031-37bb-49a0-992d-b7cf37724ab6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7629d6f7-fd1d-083a-8093-2b9d2fcdedaa
* Version Independent ID: 6a1c17a9-a22b-cce4-14fe-ee1b38fb6b59
* Content: [Data flow](https://learn.microsoft.com/en-us/dynamics365/customer-voice/data-flow)
* Content Source: [cv-docs/data-flow.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/data-flow.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @diyd365. This issue has been assigned to the doc author for review.

**Comment by sbmjais** [comment]
Thanks for the feedback. The image is updated now. Closing this issue.
