### ISSUE TITLE
OUTDATED

### ISSUE THREAD

**Issue by brcox9090** [MicrosoftDocs/customer-voice#70]
Update your pages when you update your products so that the pages are relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dff4c66-23f7-d3d1-f60c-db15608b9f3b
* Version Independent ID: cbde5db2-7471-723b-9b6b-9d055941ff36
* Content: [Create a branching rule for a survey](https://learn.microsoft.com/en-us/dynamics365/customer-voice/create-branching-rule)
* Content Source: [cv-docs/create-branching-rule.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/create-branching-rule.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @brcox9090. This issue has been assigned to the doc author for review.

**Comment by sbmjais** [comment]
Thanks for the feedback. The document is updated. Closing this issue.
